[package]
name = "drawbridge-name"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[dependencies]
# Internal dependencies
drawbridge-tags = { path = "../tags" }
drawbridge-tree = { path = "../tree" }

# External dependencies
axum = { version = "0.5.0" }
tower = { version = "0.4.12" }
